#!/bin/bash

INIT_UVC=true
FB_DEVICE="/dev/fb0"
SET_FPS="30"
SHOW_FPS=false

FB_WIDTH=$(cat /sys/class/graphics/fb0/virtual_size | cut -d, -f1)
FB_HEIGHT=$(cat /sys/class/graphics/fb0/virtual_size | cut -d, -f2)

UVC_FORMATS=(
    "uncompressed:u:${SET_FPS}:${FB_WIDTH}:${FB_HEIGHT}"
)
