#!/bin/bash

/usr/bin/v4l2-ctl -c auto_exposure=0
/usr/bin/v4l2-ctl -c auto_exposure_bias=8
/usr/bin/v4l2-ctl -c contrast=10
/usr/bin/v4l2-ctl -c video_bitrate=25000000

sudo /home/pi/uvc-gadget/gadget-run.sh conf-camera-mjpeg conf-serial
